### ISSUE TITLE
Problems after updating to 2.2.5

### ISSUE THREAD

**Issue by lysdioden** [spkesDE/com.spkes.telegramNotifications#19]
after updating to 2.2.5 the app doesn't work 
![Screenshot_20230303_175019_Homey](https://user-images.githubusercontent.com/119966816/222779791-8067334a-4eea-43cd-9009-56f0518f9a92.jpg)

**Comment by spkesDE** [comment]
Please create a diagnostic report and try to restart the app

**Comment by lysdioden** [comment]
> Please create a diagnostic report and try to restart the app

741866c4-5295-40da-b11c-ce94834c99c2

**Comment by spkesDE** [comment]
Could you try to install BLL and try again? https://homey.app/a/net.i-dev.betterlogic/test

**Comment by lysdioden** [comment]
Yes, it worked. Thanks for the help!

**Comment by lysdioden** [comment]
Yes, it worked. Thanks for the help!
