### ISSUE TITLE
Add Users

### ISSUE THREAD

**Issue by Smoothtaker** [spkesDE/com.spkes.telegramNotifications#20]
Created a new bot. But the list of users is empty.
Tried to create a second bot. But the issue is the same, no user will be added.

The token is green, so this should be working. 

Diagnostic report. 
44d60e4d-6543-40da-9c51-31518d82ac65

**Comment by spkesDE** [comment]
Hey @Smoothtaker,

the first start was successful at 8:48.
The second start was unsuccessful at 8:58 with a wrong token.

Did you run the /start command to the bot?

**Comment by Smoothtaker** [comment]
***@***.***

**Comment by Smoothtaker** [comment]
Not sure if the image was sent correctly by email. 
![image](https://user-images.githubusercontent.com/127098563/227899968-8908b5f3-7857-4802-a4ed-5e587078f0ec.png)

**Comment by spkesDE** [comment]
That the BotFather bot. you have to find your own bot in Telegram. Somewhere in this chat is a @<you_bot_name>, click on that and send /start to it if you have setup the token right inside the Telegram App Settings

**Comment by Smoothtaker** [comment]
Thankyou! That was it!
