### ISSUE TITLE
Switch Framework to grammy.dev

### ISSUE THREAD

**Issue by enyineer** [spkesDE/com.spkes.telegramNotifications#25]
[grammy.dev](https://grammy.dev/) is a Telegram Bot Framework which has a highly active Community and a great ecosystem for Bot development.

We want to change the underlying Bot Framework to grammy.dev to improve the future development of the Telegram App for Homey.

**Comment by spkesDE** [comment]
I have changed the title to 3.0.0, since we are currently at version 2.7.1

**Comment by enyineer** [comment]
I created a milestone and will create multiple issues for each requirement. Please add more if you have some good ideas 🙂
